name: Build OpenTranslator

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build Windows executable
        run: |
          pyinstaller --noconfirm --onefile --windowed ^
            --name "OpenTranslator" ^
            --icon "icon.ico" ^
            --add-data "icon.ico;." ^
            --add-data "icon.png;." ^
            --add-data "translator.py;." ^
            --hidden-import "PyQt6.QtCore" ^
            --hidden-import "PyQt6.QtGui" ^
            --hidden-import "PyQt6.QtWidgets" ^
            --hidden-import "PyQt6.QtNetwork" ^
            --hidden-import "PyQt6.QtWebEngineCore" ^
            --hidden-import "PyQt6.QtWebEngineWidgets" ^
            --collect-all "PyQt6" ^
            --collect-all "PyQt6-Qt6" ^
            --collect-all "PyQt6-sip" ^
            --collect-all "PyQt6-WebEngine" ^
            "run.py"

      - name: Zip Windows Release
        run: |
          cd dist
          Compress-Archive -Path OpenTranslator.exe -DestinationPath OpenTranslator-Windows.zip

      - name: Upload Windows Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/OpenTranslator-Windows.zip

  build-macos:
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build macOS application
        run: |
          chmod +x build_mac.sh
          ./build_mac.sh

      - name: Zip macOS Release
        run: |
          cd dist
          zip -r OpenTranslator-macOS.zip OpenTranslator.app

      - name: Upload macOS Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/OpenTranslator-macOS.zip
